sudo: false
language: node_js

notifications:
  email: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - /\d+\.\d+(\.\d+)?(-\S*)?$/

matrix:
  fast_finish: true

node_js:
  - 'node'
  - '10'
  - '8'
  - '6'
